// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loggingevent.proto

package log

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoggingEvent_LEVEL int32

const (
	LoggingEvent_TRACE LoggingEvent_LEVEL = 0
	LoggingEvent_DEBUG LoggingEvent_LEVEL = 1
	LoggingEvent_INFO  LoggingEvent_LEVEL = 2
	LoggingEvent_WARN  LoggingEvent_LEVEL = 3
	LoggingEvent_ERROR LoggingEvent_LEVEL = 4
)

var LoggingEvent_LEVEL_name = map[int32]string{
	0: "TRACE",
	1: "DEBUG",
	2: "INFO",
	3: "WARN",
	4: "ERROR",
}
var LoggingEvent_LEVEL_value = map[string]int32{
	"TRACE": 0,
	"DEBUG": 1,
	"INFO":  2,
	"WARN":  3,
	"ERROR": 4,
}

func (x LoggingEvent_LEVEL) String() string {
	return proto.EnumName(LoggingEvent_LEVEL_name, int32(x))
}
func (LoggingEvent_LEVEL) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_loggingevent_cc4a3434089ba7be, []int{0, 0}
}

type LoggingEvent struct {
	ThreadName           string             `protobuf:"bytes,1,opt,name=thread_name,json=threadName,proto3" json:"thread_name,omitempty"`
	Level                LoggingEvent_LEVEL `protobuf:"varint,2,opt,name=level,proto3,enum=loggingevent.LoggingEvent_LEVEL" json:"level,omitempty"`
	Message              string             `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	LoggerName           string             `protobuf:"bytes,4,opt,name=logger_name,json=loggerName,proto3" json:"logger_name,omitempty"`
	TimeStamp            uint64             `protobuf:"varint,5,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	CallerFileName       string             `protobuf:"bytes,6,opt,name=caller_file_name,json=callerFileName,proto3" json:"caller_file_name,omitempty"`
	CallerClassName      string             `protobuf:"bytes,7,opt,name=caller_class_name,json=callerClassName,proto3" json:"caller_class_name,omitempty"`
	CallerMethodName     string             `protobuf:"bytes,8,opt,name=caller_method_name,json=callerMethodName,proto3" json:"caller_method_name,omitempty"`
	CallerLineIndex      int32              `protobuf:"varint,9,opt,name=caller_line_index,json=callerLineIndex,proto3" json:"caller_line_index,omitempty"`
	ErrorTraceStack      string             `protobuf:"bytes,10,opt,name=error_trace_stack,json=errorTraceStack,proto3" json:"error_trace_stack,omitempty"`
	ServiceName          string             `protobuf:"bytes,11,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LoggingEvent) Reset()         { *m = LoggingEvent{} }
func (m *LoggingEvent) String() string { return proto.CompactTextString(m) }
func (*LoggingEvent) ProtoMessage()    {}
func (*LoggingEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_loggingevent_cc4a3434089ba7be, []int{0}
}
func (m *LoggingEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoggingEvent.Unmarshal(m, b)
}
func (m *LoggingEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoggingEvent.Marshal(b, m, deterministic)
}
func (dst *LoggingEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoggingEvent.Merge(dst, src)
}
func (m *LoggingEvent) XXX_Size() int {
	return xxx_messageInfo_LoggingEvent.Size(m)
}
func (m *LoggingEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_LoggingEvent.DiscardUnknown(m)
}

var xxx_messageInfo_LoggingEvent proto.InternalMessageInfo

func (m *LoggingEvent) GetThreadName() string {
	if m != nil {
		return m.ThreadName
	}
	return ""
}

func (m *LoggingEvent) GetLevel() LoggingEvent_LEVEL {
	if m != nil {
		return m.Level
	}
	return LoggingEvent_TRACE
}

func (m *LoggingEvent) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoggingEvent) GetLoggerName() string {
	if m != nil {
		return m.LoggerName
	}
	return ""
}

func (m *LoggingEvent) GetTimeStamp() uint64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *LoggingEvent) GetCallerFileName() string {
	if m != nil {
		return m.CallerFileName
	}
	return ""
}

func (m *LoggingEvent) GetCallerClassName() string {
	if m != nil {
		return m.CallerClassName
	}
	return ""
}

func (m *LoggingEvent) GetCallerMethodName() string {
	if m != nil {
		return m.CallerMethodName
	}
	return ""
}

func (m *LoggingEvent) GetCallerLineIndex() int32 {
	if m != nil {
		return m.CallerLineIndex
	}
	return 0
}

func (m *LoggingEvent) GetErrorTraceStack() string {
	if m != nil {
		return m.ErrorTraceStack
	}
	return ""
}

func (m *LoggingEvent) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func init() {
	proto.RegisterType((*LoggingEvent)(nil), "loggingevent.LoggingEvent")
	proto.RegisterEnum("loggingevent.LoggingEvent_LEVEL", LoggingEvent_LEVEL_name, LoggingEvent_LEVEL_value)
}

func init() { proto.RegisterFile("loggingevent.proto", fileDescriptor_loggingevent_cc4a3434089ba7be) }

var fileDescriptor_loggingevent_cc4a3434089ba7be = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xcf, 0xcf, 0xd2, 0x30,
	0x18, 0xc7, 0xdd, 0xcb, 0x06, 0xec, 0x81, 0xe0, 0xec, 0x69, 0x17, 0xe3, 0xe4, 0xe2, 0x62, 0xcc,
	0x0e, 0x9a, 0x78, 0xd2, 0x03, 0xe0, 0x30, 0x24, 0x13, 0x4c, 0x41, 0x3d, 0x2e, 0x65, 0x3c, 0x8c,
	0x86, 0x76, 0xc3, 0x6e, 0xa2, 0x7f, 0xbd, 0x31, 0x6d, 0x47, 0x82, 0xef, 0xad, 0xfb, 0x3c, 0x9f,
	0x7c, 0xbf, 0xeb, 0x0f, 0x20, 0xa2, 0x2e, 0x4b, 0x5e, 0x95, 0x78, 0xc5, 0xaa, 0x4d, 0x2e, 0xaa,
	0x6e, 0x6b, 0x32, 0xbe, 0x67, 0xd3, 0xbf, 0x3d, 0x18, 0x67, 0x16, 0xa4, 0x1a, 0x90, 0x17, 0x30,
	0x6a, 0x4f, 0x0a, 0xd9, 0x21, 0xaf, 0x98, 0xc4, 0xd0, 0x89, 0x9c, 0xd8, 0xa7, 0x60, 0xd1, 0x9a,
	0x49, 0x24, 0xef, 0xc1, 0x13, 0x78, 0x45, 0x11, 0x3e, 0x44, 0x4e, 0x3c, 0x79, 0x1b, 0x25, 0xff,
	0x75, 0xdc, 0x67, 0x25, 0x59, 0xfa, 0x3d, 0xcd, 0xa8, 0xd5, 0x49, 0x08, 0x03, 0x89, 0x4d, 0xc3,
	0x4a, 0x0c, 0x7b, 0x26, 0xf4, 0xf6, 0xa9, 0x2b, 0x75, 0x06, 0x2a, 0x5b, 0xe9, 0xda, 0x4a, 0x8b,
	0x4c, 0xe5, 0x73, 0x80, 0x96, 0x4b, 0xcc, 0x9b, 0x96, 0xc9, 0x4b, 0xe8, 0x45, 0x4e, 0xec, 0x52,
	0x5f, 0x93, 0xad, 0x06, 0x24, 0x86, 0xa0, 0x60, 0x42, 0xa0, 0xca, 0x8f, 0x5c, 0xa0, 0x0d, 0xe9,
	0x9b, 0x90, 0x89, 0xe5, 0x4b, 0x2e, 0xd0, 0x04, 0xbd, 0x86, 0x67, 0x9d, 0x59, 0x08, 0xd6, 0x34,
	0x56, 0x1d, 0x18, 0xf5, 0xa9, 0x1d, 0x2c, 0x34, 0x37, 0xee, 0x1b, 0x20, 0x9d, 0x2b, 0xb1, 0x3d,
	0xd5, 0xdd, 0x79, 0x0c, 0x8d, 0xdc, 0xf5, 0x7d, 0x31, 0x83, 0x47, 0xc9, 0x82, 0x57, 0x98, 0xf3,
	0xea, 0x80, 0x7f, 0x42, 0x3f, 0x72, 0x62, 0xef, 0x96, 0x9c, 0xf1, 0x0a, 0x57, 0x1a, 0x6b, 0x17,
	0x95, 0xaa, 0x55, 0xde, 0x2a, 0x56, 0x98, 0x5d, 0x15, 0xe7, 0x10, 0xec, 0x5f, 0x98, 0xc1, 0x4e,
	0xf3, 0xad, 0xc6, 0xe4, 0x25, 0x8c, 0x1b, 0x54, 0x57, 0x5e, 0x74, 0xfb, 0x1a, 0x19, 0x6d, 0xd4,
	0x31, 0x5d, 0x3d, 0xfd, 0x00, 0x9e, 0x39, 0x68, 0xe2, 0x83, 0xb7, 0xa3, 0xb3, 0x45, 0x1a, 0x3c,
	0xd1, 0xcb, 0x4f, 0xe9, 0xfc, 0xdb, 0xe7, 0xc0, 0x21, 0x43, 0x70, 0x57, 0xeb, 0xe5, 0x26, 0x78,
	0xd0, 0xab, 0x1f, 0x33, 0xba, 0x0e, 0x7a, 0x7a, 0x9c, 0x52, 0xba, 0xa1, 0x81, 0x3b, 0xff, 0x08,
	0xaf, 0x8a, 0x5a, 0x26, 0xec, 0x67, 0x72, 0x54, 0x4c, 0xe2, 0xef, 0x5a, 0x9d, 0x13, 0x94, 0x7b,
	0x3c, 0xdc, 0xee, 0xd5, 0x3e, 0x9b, 0xfd, 0xaf, 0xe3, 0x9c, 0xdc, 0x5f, 0xee, 0x57, 0x4d, 0x9b,
	0x7d, 0xdf, 0x4c, 0xdf, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x53, 0xfb, 0x98, 0x6a, 0x02,
	0x00, 0x00,
}
